name: face-anon-simple
dependencies:
  - python=3.8.18
  - pip
  - pip:
    - torch==2.1
    - torchvision==0.16.0
    - huggingface_hub<0.26.0
    - diffusers==0.25.1
    - transformers==4.46.1
    - accelerate==1.0.1
    - datasets==3.1.0
    - xformers==0.0.22.post7
    - bitsandbytes==0.44.1
    - ipykernel==6.29.5
    - face-alignment==1.4.1
    - albumentations==1.4.1
    - wandb==0.16.3
